# Generated by Django 5.0.8 on 2024-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('title', models.CharField(max_length=255)),
                ('content', models.FloatField()),
                ('button_name', models.CharField(max_length=200)),
                ('button_link', models.CharField(max_length=200)),
            ],
        ),
    ]
