# Generated by Django 5.0.8 on 2024-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
