# Generated by Django 5.0.8 on 2024-11-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_videomodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='exploreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('brand_name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('btn_name', models.CharField(max_length=200)),
                ('btn_link', models.CharField(max_length=200)),
                ('buy_name', models.CharField(max_length=200)),
                ('buy_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='videomodel',
            old_name='button_link',
            new_name='btn_link',
        ),
        migrations.RenameField(
            model_name='videomodel',
            old_name='button_name',
            new_name='btn_name',
        ),
    ]
