# Generated by Django 5.0.8 on 2024-11-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_exploremodel_rename_button_link_videomodel_btn_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
