# Generated by Django 5.0.8 on 2024-12-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customermodel_delete_adminlogin_delete_exploremodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
