# Generated by Django 5.0.8 on 2024-12-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='image',
        ),
    ]
