# Generated by Django 5.0.8 on 2024-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_mediamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
