# Generated by Django 5.0.8 on 2025-06-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
