# Generated by Django 5.0.8 on 2025-06-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_adminuser_password_adminuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='user',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
