# Generated by Django 5.0.8 on 2025-06-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_adminuser_is_admin_remove_adminuser_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='email',
        ),
    ]
