# Generated by Django 5.0.8 on 2025-06-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_adminuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
