# Generated by Django 5.0.8 on 2025-06-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_adminuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
